name: Send Notion Tasks to Slack

on:
  schedule:
    - cron: "0 12 * * *"   # 12h UTC -> 9h São Paulo (manhã)
    - cron: "0 21 * * *"   # 21h UTC -> 18h São Paulo (noite)
  workflow_dispatch:        # permite rodar manualmente também

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: |
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST "https://notion-slack-send-7eme0ljrm-softis.vercel.app/api/send")
          http_code=$(echo $response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          body=$(echo $response | sed -e 's/HTTPSTATUS:.*//g')
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ $http_code -ne 200 ]; then
            echo "Erro na requisição!"
            exit 1
          else
            echo "✅ Mensagem enviada com sucesso!"
          fi